debug: true
server:
  port: 8081
  servlet:
    multipart:
  max-file-size: 500KB
  max-request-size: 500KB


spring:
  datasource:
    url: jdbc:h2:mem:blog
    driverClassName: org.h2.Driver
    username: postgres
    password: admin
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create

jwt:
  jwtSecret: blogjwtcode
  jwtExpirationInMs: 604800000